---
name: deploy

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: tastebit/leasefront

jobs:
  publish:
    name: Build & Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          tags: ${{ env.IMAGE_NAME }}
          push: true

      - name: Overwrite docker-compose.yaml on host
        # scp repo's docker compose to host machine
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_WORKDIR }}
      - name: Creds cleanup
        run: rm -rf ~/.ssh

  deploy:
    needs: publish
    name: Deploy Image to LeaseFront
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # TODO: CHANGE SSH PORT
          # port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            mkdir -p ${{ secrets.SSH_WORKDIR }} 
            cd ${{ secrets.SSH_WORKDIR }}
            docker-compose down --rmi local
            docker-compose pull
            docker-compose up -d
            exit

      - name: cleanup
        run: rm -rf ~/.ssh
